site_name: Bruce comments on IBM Cloud
nav:
  - Home: 
    - Index: index.md
    - Two: test.md
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.annotation
    - content.code.copy
  language: en
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.smartsymbols
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
copyright: Copyright &copy; 2023 Bruce Kyle | All opinions and views are my own 
extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://linkedin.com/in/brucedkyle
    - icon: fontawesome/brands/github
      link: https://github.com/brucedkyle/
