site_name: IBM Cloud® for Partners
nav:
  - Home: 
    - Home page: index.md
    - Getting started: ./cloud/getstarted.md
    - Financial Services Cloud: ./financial-services.md
    - About: about.md
  - Storage:
      - Cloud Object Storage: ./cloud/storage.md
  - IaaS:
    - Cloud Native:
      - Virtual Private Cloud (VPC) in the Public Cloud: ./cloud/vpc.md
      - VPC Architectures: ./cloud/vpc-architecture.md
    - Extended Enterprise:
      - PowerVS: ./cloud/powervs.md
      - Deploy PowerVS: ./cloud/powervs-vpc.md
      - PowerVS Demo Guide~: https://ibm.github.io/SalesEnablement-PowerVS-L3/
    - Bare Metal Servers: 
      - Overview: ./cloud/baremetal.md
      - Bare Metal Classic: ./cloud/baremetal-classic.md
      - Bare Metal VPC: ./cloud/baremetal-vpc.md
      - Transit Gateway: ./cloud/transitgateway.md
    - VMware on IBM Cloud:
      - VMware offerings: ./cloud/vmware.md
      - VMware as a Managed Service on Bare Metal: ./cloud/vmware-as-a-service.md
      - Bare Metal Classic for VMware: ./cloud/baremetal-vmware.md
      - VMware on Virtual Private Cloud (VPC): ./cloud/baremetal-vpc-vmware.md
      - VMware Regulated Workloads on IBM Cloud: ./cloud/vmware-regulated.md
      - VMware Cloud Foundation on IBM Cloud: ./cloud/vmware-cloud-foundation.md
      - VMware Solutions Shared: ./cloud/vmware-shared.md
  - PaaS:
      - Red Hat OpenShift on IBM Cloud: ./paas/openshift.md
      - Learning Kubernetes: ./paas/gettingstartedk8s.md
  - Security:
    - Key and Hyper Protect Services:
        - Key Protect: ./security/keyprotect.md
        - Key Protect tutorials: ./security/keyprotect-tutorials.md
        - Hyper Protect Crypto Services: ./security/hyperprotect.md
        - Hyper Protect tutorials: ./security/hyperprotect-tutorials.md
        - Unified Key: ./security/unifiedkey.md
    - Cloud Security and Compliance:
      - Security Architecture: https://cloud.ibm.com/docs/framework-financial-services?topic=framework-financial-services-about
      - Cloud Security and Compliance Center: ./security/securityandcompliance.md
  - Z:
      - Mainframe modernization: ./mainframe/modernization.md
      - Getting started with mainframe: ./mainframe/getstarted.md
      - Modernization scenarios:
        - App Modernization:
            - Modernization patterns: ./mainframe/appmodernpatterns.md
            - Discovery: ./mainframe/discovery.md
            - DevTest: ./mainframe/devtest.md
            - Generative AI: ./mainframe/genai.md
            - Containers on Z: ./mainframe/containers.md
            - API: ./mainframe/api.md
        - Enterprise DevOps: ./mainframe/devops.md
        - Security: ./mainframe/security.md
        - Sustainability: ./mainframe/sustainability.md
        - AI: ./mainframe/ai.md
      - Tooling:
          - LinuxONE: ./mainframe/linuxone.md
          - Hyper Protect Virtual Servers for VPC on LinuxONE: ./mainframe/hyper-protect-vs.md
          - IBM Z and Cloud Modernization Stack: ./mainframe/stack.md
          - IBM Wazi as a Service overview: ./mainframe/wazi.md
          - Wazi Code: ./mainframe/wazicode.md
          - Wazi Analyze: ./mainframe/analyze.md
          - Wazi Sandbox: ./mainframe/sandbox.md
          - Wazi Deploy: ./mainframe/deploy.md
          - Wazi Image Builder: ./mainframe/imagebuilder.md
          - DevOps using Wazi: ./mainframe/wazi-devops.md
          - Wazi as a Service setup: ./mainframe/wazisetup.md
          - z/OS Connect: ./mainframe/zOSconnect.md
          - z/OS Cloud Broker: ./mainframe/cloudbroker.md
          - z/OS on IBM Cloud: ./mainframe/ibmcloud.md
          - Red Hat OpenShift on Z: ./mainframe/openshift.md
          - AI tools on Z: ./mainframe/aitools.md
      - Refactoring:
          - Application Discovery and Delivery Intelligence (ADDI): ./mainframe/addi.md
          - watsonx Code Assistant for Z: ./mainframe/watsonxcodeassist.md
          - watsonx Code Assistant for Z architecture: ./mainframe/watsonxcodeassistarchitecture.md
          - IBM Open Enterprise SDKs: ./mainframe/openenterprise.md
  - watsonx:
      - watsonx as a service: ./watsonx/watsonxai.md
extra_css:
  - stylesheets/extra.css
theme: 
  name: material
  font:
      text: Nanum Gothic
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.annotation
    - content.code.copy
    - header.autohide
    - navigation.footer
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.share
  language: en
  icon: 
      repo: fontawesome/brands/github
      edit: material/pencil 
      view: material/eye
  logo: ./media/R.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search:
      lang: en
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.smartsymbols
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
copyright: Copyright &copy; 2023 IBM | However, all opinions and views are my own 
extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://linkedin.com/in/brucedkyle
    - icon: fontawesome/brands/github
      link: https://github.com/brucedkyle/
    - icon: fontawesome/solid/envelope
      link: mailto:bruce.kyle@ibm.com
repo_url: https://github.com/brucedkyle/ibmcloud_for_isvs
repo_name: brucedkyle/ibmcloud_for_isvs
edit_uri: edit/main/docs/